include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - "lib/l10n/gen/**"
    - "**/*.g.dart"
    - "**/*.router.dart"
    - "**/*.locator.dart"
    - "**/*.form.dart"
    - "**/*.logger.dart"
    - "**/*.dialogs.dart"
    - "**/*.bottomsheets.dart"

linter:
  rules:
    public_member_api_docs: false
