import 'package:flutter_gemma/flutter_gemma.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';
import 'package:offline_sync/services/embedding_service.dart';
import 'package:shared_preferences/shared_preferences.dart';

class _MockEmbeddingModel extends Mock implements EmbeddingModel {}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('EmbeddingService -', () {
    setUp(() {
      SharedPreferences.setMockInitialValues({});
    });

    test(
      'surfaces a clear error when no active embedder is configured',
      () async {
        final service = EmbeddingService();

        await expectLater(
          () => service.generateEmbedding('test query'),
          throwsA(
            isA<StateError>().having(
              (error) => error.message,
              'message',
              contains('No active embedding model set'),
            ),
          ),
        );
      },
    );

    test('returns the embedding generated by the active embedder', () async {
      final embedder = _MockEmbeddingModel();
      const embedding = [0.1, 0.2, 0.3];
      when(
        () => embedder.generateEmbedding('hello world'),
      ).thenAnswer((_) async => embedding);

      final service = EmbeddingService(
        activeEmbedderLoader: () async => embedder,
      );

      expect(
        await service.generateEmbedding('hello world'),
        equals(embedding),
      );
    });
  });
}
