import 'package:flutter_gemma/flutter_gemma.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';
import 'package:offline_sync/app/app.locator.dart';
import 'package:offline_sync/services/embedding_service.dart';
import 'package:offline_sync/services/rag_settings_service.dart';
import 'package:shared_preferences/shared_preferences.dart';

class _MockEmbeddingModel extends Mock implements EmbeddingModel {}

class _MockRagSettingsService extends Mock implements RagSettingsService {}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('EmbeddingService -', () {
    setUp(() {
      SharedPreferences.setMockInitialValues({});
    });

    test(
      'surfaces a clear error when no active embedder is configured',
      () async {
        await FlutterGemma.clearActiveEmbeddingIdentity();
        final service = EmbeddingService();

        await expectLater(
          () => service.generateEmbedding('test query'),
          throwsA(
            isA<StateError>().having(
              (error) => error.message,
              'message',
              contains('No active embedding model set'),
            ),
          ),
        );
      },
    );

    test('returns the embedding generated by the active embedder', () async {
      final embedder = _MockEmbeddingModel();
      const embedding = [0.1, 0.2, 0.3];
      when(
        () => embedder.generateEmbedding('hello world'),
      ).thenAnswer((_) async => embedding);

      final service = EmbeddingService(
        activeEmbedderLoader: () async => embedder,
      );

      expect(await service.generateEmbedding('hello world'), equals(embedding));
    });

    test('pins the active model identity for a supplied embedder', () async {
      final embedder = _MockEmbeddingModel();
      final settings = _MockRagSettingsService();
      when(() => settings.activeEmbeddingModelId).thenReturn('embedding-a');
      locator.registerSingleton<RagSettingsService>(settings);
      addTearDown(locator.reset);
      final service = EmbeddingService(
        activeEmbedderLoader: () async => embedder,
      );

      final pinned = await service.pinActiveModel();

      expect(pinned.id, 'embedding-a');
      expect(pinned.model, same(embedder));
    });

    test('rejects an empty active embedding identity', () async {
      final settings = _MockRagSettingsService();
      when(() => settings.activeEmbeddingModelId).thenReturn('');
      locator.registerSingleton<RagSettingsService>(settings);
      addTearDown(locator.reset);
      final service = EmbeddingService(
        activeEmbedderLoader: () async => _MockEmbeddingModel(),
      );

      await expectLater(
        service.pinActiveModel(),
        throwsA(isA<StateError>()),
      );
    });
  });
}
